### ISSUE TITLE
Kahoot reject authentication request: Unknown Client

### ISSUE THREAD

**Issue by adamsong** [Arccotangent/kahoot-hack#1] opened 2016-08-11 12:00 UTC
When connecting to a kahoot game I get the error: 
    `[{"error":"402::Unknown client","successful":false,"advice":{"interval":0,"reconnect":"handshake"},"channel":"/meta/connect"}]`

**Comment by Arccotangent** [comment] 2016-08-14 02:25
Looking into this, Kahoot has had some changes since this tool was updated.
I should have the tool fixed very soon.

**Comment by Arccotangent** [comment] 2016-09-05 19:55
I've just confirmed that the tool is working again, closing this issue.

**Closed by Arccotangent** 2016-09-05 19:55 UTC
